name: GPT Review

env:
  NODE_VERSION: 18

on:
  pull_request:
    branches: ['main']
    types: [opened, synchronize, reopened]

jobs:
  gpt_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run GPT Review Action
        uses: nodify-at/gpt-pull-bot@1.0.3
        with:
          api-key: ${{ secrets.GPT_API_KEY }}
          github-token: ${{ secrets.GH_TOKEN }}
